---
title: "Running Biomass_core with a sample study area in Alberta, Canada"
author: "Eliot McIntire"
date: "19 January 2021"
output:
  pdf_document: default
editor_options:
  chunk_output_type: console
---

## Get the module

See [SpaDES-modules repository](https://github.com/PredictiveEcology/SpaDES-modules) to see how to download this and other SpaDES modules.

# Usage example

```{r setup, eval=FALSE}
workshopPath = "~/SpaDESWorkshop"
modulePath = file.path(workshopPath, "modules")
if (Sys.info()[["user"]] == "emcintir") {
  workshopPath = "c:/Eliot/GitHub"
  modulePath = file.path(workshopPath, ".")
  inputPath = file.path(workshopPath, "inputs")
  outputPath = file.path(workshopPath, "outputs")
  cachePath =  file.path(workshopPath, "cache")
}

# Set a few options
options(# this puts a generic cached data folder, so that if further projects
        #    need same dataset, it isn't re-downloaded
        reproducible.inputPaths = file.path(workshopPath, "cachedData"),

        # This is for checking the code of the module for inconsistencies or
        #   issues that may need addressing. Currently, we don't need to address any of these
        spades.moduleCodeChecks = FALSE) # Don't check code during example

if (!require("Require")) {install.packages("Require"); library(Require)}
Require(c("SpaDES.core", "PredictiveEcology/LandR@development"))

setPaths(cachePath, inputPath, modulePath, outputPath)

# Can accept the default paths, which is in a temporary locations; or use a more permanent one
moduleName <- c("Biomass_core")

# Set module pathd
setPaths(modulePath = modulePath)

# Pick a study area -- in Alberta, Canada
studyArea <- randomStudyArea(seed = 1234, size = (250^2)*100)

# Pick 5 species of tree -- default is to download all that in the Boreal forest first and then
#    crop the study area to find the ones that are actually in the study area
speciesToUse <- c("Pice_gla", "Pinu_con", "Popu_tre")
sppEquiv <- LandR::sppEquivalencies_CA
sppEquiv <- sppEquiv[LandR %in% speciesToUse]

# Get the species data from Dominic Cyr (a researcher who has worked in Canada with Landis II)
DominicCyrSpeciesTableURL <- "https://raw.githubusercontent.com/dcyr/LANDIS-II_IA_generalUseFiles/master/speciesTraits.csv"
speciesTable <- getSpeciesTable(dPath = ".", url = DominicCyrSpeciesTableURL)
# devtools::load_all("C:/Eliot/GitHub/LandR")
species <- prepSpeciesTable(speciesTable = speciesTable,
                            sppEquiv = sppEquiv,
                            areas = c("BSW", "MC"),
                            sppEquivCol = "LandR")


```

```{r setup-simList, eval=FALSE}
times <- list(start = 2011, end = 2012)

## Usage example
modules <- as.list(moduleName)
objects <- list()
paths <- getPaths()

successionTimestep <- 1L

## keep default values for most parameters
## (ommitted from this list)
parameters <- list(
  Biomass_core = list(
    ".plotInitialTime" = times$start
    , "sppEquivCol" = "LandR"
    , "successionTimestep" = successionTimestep*10
    , ".saveInitialTime" = 1
    , ".useCache" = FALSE
    , ".useParallel" = FALSE
    , ".studyAreaName" = "RandomAB"
  )
)

objects <- list(
  species = species,
  sppEquiv = sppEquiv,
  studyArea = studyArea

)
mySim <- simInit(times = times, params = parameters, modules = modules, objects = objects, paths = paths)

# Can check the Landis Traits
```

```{r run-dynamic-simulation, eval=FALSE}
mySimOut <- spades(mySim, debug = TRUE)
```

